# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
- name : ispullrequest
  value : 'false'

pool:
  vmImage: 'ubuntu-latest'
stages:
- stage: Build
  jobs:
  - job: Build
    continueOnError: true
    steps:
    - script: echo 'Test'

    - task: CmdLine@2
      displayName : print first
      inputs:
        script: echo ispullrequest:'$(ispullrequest)'
    - task: Bash@3
      displayName : set variable
      inputs:
       targetType: 'inline'
       script: |
         echo "##vso[task.setvariable variable=AppType;]WebJob"
         echo "##[debug] AppType set to WebJob"
         echo "##vso[task.setvariable variable=ispullrequest;isOutput=true]true"
    - task: CmdLine@2
      displayName : print after set variable
      inputs:
        script: echo ispullrequest:'$(ispullrequest)'
    - task: CmdLine@2
      displayName : test condition on first job
      condition: and(succeeded(), eq(variables['ispullrequest'], 'true'))
      inputs:
        script: echo ispullrequest:'$(ispullrequest)'
       
                

 
  - job: BuildDatabase
    dependsOn: Build
    displayName: Database Build
    steps:
      - checkout: none


      - task: CmdLine@2
        displayName : print variable on second job
        inputs:
         script: echo ispullrequest:'$(ispullrequest)'
      - task: CmdLine@2
        displayName : test variable on second job
        ${{ if eq(variables.ispullrequest, 'true') }}:
        inputs:
          script: echo ispullrequest:'$(ispullrequest)'
               